#!/bin/sh 
#kvm -hda ~/vms/${1} -m 512
#sudo kvm -hda vms/$1 -m 1024 -net nic,model=virtio -net tap,ifname=tap0,script=no,downscript=no
sudo kvm -hda vms/$1 -m 1024 -net tap,ifname=tap0,script=no,downscript=no
