#!/bin/bash
virt-install --connect=qemu:///system \
  --name=vm1 \
  --cpu mode=host-passthrough --vcpus=2 \
  --ram=512 \
  --disk path=/home/gui/vms/vm1.qcow2,bus=virtio,cache=none,size=20,format=qcow2 \
  --cdrom=/home/gui/iso/debian-10.2.0-amd64-netinst.iso --check all=off


