#!/bin/sh 

usage() {
  echo "$(basename $0) <vm_name>"
  exit 1
}

[ $# -ne 1 ] && usage

#kvm -hda ~/vm/${1} -m 512
#sudo kvm -hda ~/vm/$1 -m 1024 -net nic,model=virtio -net tap,ifname=tap0,script=no,downscript=no
#sudo kvm -hda ~/vm/$1 -m 1024 -net tap,ifname=tap0,script=no,downscript=no
sudo qemu-system-x86_64 -enable-kvm -hda ~/vm/debian1.qcow2 -m 1024 -net nic,model=virtio -net tap,ifname=tap0
